# Generated by Django 3.2 on 2021-06-04 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_order_price'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='UserOrder',
        ),
    ]
