# Generated by Django 3.2 on 2021-06-04 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0004_alter_order_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='UserOrder',
        ),
    ]
