# Generated by Django 3.2 on 2021-06-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0005_rename_order_userorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userorder',
            old_name='price',
            new_name='usr_price',
        ),
    ]
