# Generated by Django 3.2 on 2021-06-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0009_auto_20210605_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='products/%Y/%m/%d'),
        ),
    ]
