# Generated by Django 3.2 on 2021-06-05 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0014_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='username',
        ),
    ]
