# Generated by Django 3.2 on 2021-06-05 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0015_remove_cart_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='gotten',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userorder',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userOrder', to='api_v1.user'),
            preserve_default=False,
        ),
    ]
