# Generated by Django 3.2 on 2021-06-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0016_auto_20210605_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='gotten',
            field=models.BooleanField(default=False),
        ),
    ]
