# Generated by Django 3.2 on 2021-06-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0019_auto_20210606_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checktag',
            name='created',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='checktag',
            name='ended',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
