# Generated by Django 3.2 on 2021-06-06 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0020_auto_20210606_0659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkorder',
            old_name='cateogry_name',
            new_name='category_name',
        ),
    ]
